### PR TITLE
Fix i18n tests broken by latest Babel versions

### PR DESCRIPTION
**Pull request by vrialland**

### CODE REVIEW

**Comment by bcroq** [comment]
http://pytz.sourceforge.net/ says:
> This library differs from the documented Python API for tzinfo implementations; if you want to create local wallclock times you need to use the localize() method documented in this document.

It looks like:
`datetime.datetime(2007, 4, 1, 15, 30, tzinfo=pytz.timezone('America/Los_Angeles'))`
should be written:
`pytz.timezone('America/Los_Angeles').localize(datetime.datetime(2007, 4, 1, 15, 30))`

**Comment by bcroq** [comment]
the tests should not use timezones with daylight saving time transitions (e.g. "america/los_angeles" or Europe/Paris")

**Comment by vrialland** [comment]
Ahah I was replying to you about this :smiley:

**Comment by vrialland** [comment]
@bcroq do you see any other problems in the PR?

**Pull request merged**
